Add lora support in lmi-dist
deepjavalibrary/djl-serving pull request #1664
Opened 2024-03-23 18:27 UTC by rohithkrn

## Description ##

Add lora support in lmi-dist. 
Was waiting for https://github.com/deepjavalibrary/djl-serving/pull/1651 to be merged to create this PR to avoid merge conflicts for either PR, so got little late.

2024-03-23 23:15 UTC, davidthomas426 requested changes
Did we need to add an integration test to `llm_integration.yml`?

Like these two: https://github.com/deepjavalibrary/djl-serving/blob/0747d91fe7d6ebaba3928cb2339931597ec57087/.github/workflows/llm_integration.yml#L182-L199

2024-03-25 16:54 UTC, rohithkrn commented
I thought integration test was already included as the test details were added in `prepare.py` and `client.py` but it's not actually invoked in the wokrflow file. Added in the workflow file and tested the test locally.

2024-03-25 17:01 UTC, zachgk approved these changes

2024-03-25 17:31 UTC, davidthomas426 approved these changes

2024-03-27 01:41 UTC, merged

2024-03-27 05:18 UTC, rohithkrn commented
Testing:
1.  `python3 llm/prepare.py vllm llama-7b-unmerged-lora` - Create model dir with serving.properties
2.  `djl-serving -m test=$PWD/models/test/` - Start model server
3. `python3 llm/client.py vllm llama-7b-unmerged-lora` - Run client.

Output:
```
INFO:root:req {'inputs': 'DeepSpeed is a machine learning framework', 'parameters': {'do_sample': True, 'max_new_tokens': 100, 'details': True}, 'adapters': 'english-alpaca'}     
INFO:root:res: {"token": {"id": [363], "text": " for", "log_prob": -0.7203744053840637}}                                                                                           
{"token": {"id": [19328], "text": " rapidly", "log_prob": -6.006423473358154}}                                                                                                     
{"token": {"id": [14338], "text": " developing", "log_prob": -0.8733174204826355}}                                                                                                 
{"token": {"id": [6483], "text": " deep", "log_prob": -0.5829942226409912}}                                                                                                        
{"token": {"id": [6509], "text": " learning", "log_prob": -0.1772700846195221}}                                                                                                    
{"token": {"id": [9279], "text": " projects", "log_prob": -4.735476493835449}}                                                                                                     
{"token": {"id": [411], "text": " with", "log_prob": -3.6987128257751465}}                                                                                                         
{"token": {"id": [323], "text": " T", "log_prob": -4.931850433349609}}                                                                                                             
{"token": {"id": [6073], "text": "ensor", "log_prob": -0.003121386980637908}}                                                                                                      
{"token": {"id": [17907], "text": "Flow", "log_prob": -0.06798986345529556}}                                                                                                       
{"token": {"id": [29889], "text": ".", "log_prob": -0.33840078115463257}}                                                                                                          
{"token": {"id": [739], "text": " It", "log_prob": -0.6838171482086182}}                                                                                                           
{"token": {"id": [6911], "text": " helps", "log_prob": -4.4225921630859375}}                                                                                                       
{"token": {"id": [15592], "text": " acceler", "log_prob": -4.4303412437438965}}                                                                                                    
{"token": {"id": [403], "text": "ate", "log_prob": -0.008935937657952309}}                                                                                                         
{"token": {"id": [596], "text": " your", "log_prob": -3.7762961387634277}}                                                                                                         
{"token": {"id": [2060], "text": " project", "log_prob": -2.7581677436828613}}                                                                                                     
{"token": {"id": [491], "text": " by", "log_prob": -0.9058602452278137}}                                                                                                           
{"token": {"id": [6336], "text": " automatically", "log_prob": -3.5371432304382324}}                                                                                               
{"token": {"id": [14655], "text": " generating", "log_prob": -1.1503322124481201}}                                                                                                 
{"token": {"id": [263], "text": " a", "log_prob": -2.9815151691436768}}                                                                                                            
{"token": {"id": [6483], "text": " deep", "log_prob": -2.2973010540008545}}                                                                                                        
{"token": {"id": [6509], "text": " learning", "log_prob": -0.1423019915819168}}                                                                                                    
{"token": {"id": [848], "text": " data", "log_prob": -8.231603622436523}}                                                                                                          
{"token": {"id": [16439], "text": " pipeline", "log_prob": -0.3384842276573181}}                                                                                                   
{"token": {"id": [363], "text": " for", "log_prob": -3.3789806365966797}}                                                                                                          
{"token": {"id": [366], "text": " you", "log_prob": -0.43585845828056335}}                                                                                                         
{"token": {"id": [29889], "text": ".", "log_prob": -0.6496286392211914}} 
{"token": {"id": [739], "text": " It", "log_prob": -1.621570110321045}}
{"token": {"id": [884], "text": " also", "log_prob": -1.0753426551818848}}
{"token": {"id": [4327], "text": " transform", "log_prob": -10.018915176391602}}
{"token": {"id": [29879], "text": "s", "log_prob": -0.002663519000634551}}
{"token": {"id": [596], "text": " your", "log_prob": -0.7177503108978271}}
{"token": {"id": [848], "text": " data", "log_prob": -1.3260821104049683}}
{"token": {"id": [304], "text": " to", "log_prob": -2.8536102771759033}}
{"token": {"id": [278], "text": " the", "log_prob": -1.0607094764709473}}
{"token": {"id": [323], "text": " T", "log_prob": -3.7832627296447754}}
{"token": {"id": [6073], "text": "ensor", "log_prob": -0.04112643748521805}}
{"token": {"id": [17907], "text": "Flow", "log_prob": -0.014746476896107197}}
{"token": {"id": [1881], "text": " input", "log_prob": -3.394742965698242}}
{"token": {"id": [3402], "text": " format", "log_prob": -0.39776530861854553}}
{"token": {"id": [322], "text": " and", "log_prob": -1.0609197616577148}}
{"token": {"id": [5994], "text": " optim", "log_prob": -2.9944262504577637}}
{"token": {"id": [7093], "text": "izes", "log_prob": -0.02547975815832615}}
{"token": {"id": [278], "text": " the", "log_prob": -1.0385828018188477}}
{"token": {"id": [775], "text": " code", "log_prob": -2.686676502227783}}
{"token": {"id": [363], "text": " for", "log_prob": -0.49202829599380493}}
{"token": {"id": [8473], "text": " faster", "log_prob": -1.941789150238037}}
{"token": {"id": [8225], "text": " execution", "log_prob": -0.4195268750190735}}
{"token": {"id": [29889], "text": ".", "log_prob": -0.17166292667388916}}
{"token": {"id": [13], "text": "\n", "log_prob": -0.9909327030181885}}
{"token": {"id": [7658], "text": "Hel", "log_prob": -8.767471313476562}}
{"token": {"id": [567], "text": "ps", "log_prob": -0.12685076892375946}}
{"token": {"id": [2693], "text": " develop", "log_prob": -4.358809947967529}}
{"token": {"id": [6483], "text": " deep", "log_prob": -0.2834896147251129}}
{"token": {"id": [6509], "text": " learning", "log_prob": -0.010074126534163952}}
{"token": {"id": [9279], "text": " projects", "log_prob": -0.13614574074745178}}
{"token": {"id": [411], "text": " with", "log_prob": -1.838451623916626}}
{"token": {"id": [323], "text": " T", "log_prob": -0.23180364072322845}}
{"token": {"id": [6073], "text": "ensor", "log_prob": -0.001982629531994462}}
{"token": {"id": [1731], "text": "flow", "log_prob": -3.8198537826538086}}
{"token": {"id": [29889], "text": ".", "log_prob": -0.7419525384902954}}
{"token": {"id": [13], "text": "\n", "log_prob": -0.2318771 [...]