[tnx] Read-only Neuron cache workaround for SM
deepjavalibrary/djl-serving pull request #1879
Opened 2024-05-06 23:46 UTC by a-ys

## Description ##

This PR adds the following logic: When loading a Neuron model, if the currently set Neuron cache directory is read-only, the model loader will copy the contents of this read-only directory to the default Neuron cache location and use the default Neuron cache location for compiling the model. 

This enables the ability for users to pass in a Neuron cache directory with pre-prepared graphs in the input model location (`/opt/ml/model`) on a SageMaker endpoint, which is read-only.

### Current Behavior
Currently, if a user attempts to pass a Neuron cache in the input model directory they will encounter an error like:
```
[WARN ] PyProcess - W-100-model-stderr: File "/usr/local/lib/python3.9/dist-packages/libneuronxla/neuron_cc_cache.py", line 118, in __enter__
[WARN ] PyProcess - W-100-model-stderr: self.lock_fd = open(self.lock_path, 'w')
[WARN ] PyProcess - W-100-model-stderr: OSError: [Errno 30] Read-only file system: '/opt/ml/model/neuron_cache/lock'
```
Where the Neuron compiler attempts to write a lock file to the cache directory. This occurs even if the correct graphs are passed, where if they were read in, no additional compilation would have been required.

### Security
The logic would allow a user to copy any read-only directory to exactly `/var/tmp/neuron-compile-cache` when using the LMI container. However, I believe a user would already be able to do this when using a custom inference handler.

2024-05-07 02:19 UTC, Lokiiiiii requested changes

2024-05-07 02:19 UTC, Lokiiiiii commented on engines/python/setup/djl_python/neuron_utils/model_loader.py
> +        cache_dir = os.environ.get("NEURON_COMPILE_CACHE_URL")
The `NEURON_COMPILE_CACHE_URL` can also be a S3 location. This code logic should only be selectively applied to local directories.

2024-05-11 23:01 UTC, tosterberg approved these changes

2024-05-13 18:53 UTC, Lokiiiiii approved these changes

2024-05-14 20:18 UTC, merged